require('../../scripts/build.cjs');const fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'../..'),out=path.join(root,'artifacts/n8n');fs.mkdirSync(out,{recursive:true});
const read=role=>JSON.parse(fs.readFileSync(path.join(root,'dist',role+'-workflow.json')));
const child=read('child');child.id='localMockAuthor';child.name='LOCAL MOCK - Author';child.settings={...child.settings,callerPolicy:'any',saveDataSuccessExecution:'all',saveDataErrorExecution:'all'};
for(const n of child.nodes)if(n.type==='n8n-nodes-base.httpRequest'){n.parameters.authentication='none';delete n.parameters.genericAuthType;delete n.parameters.nodeCredentialType;delete n.parameters.bodyParameters;n.parameters.url='http://127.0.0.1:5689/mock';n.parameters.sendBody=true;n.parameters.specifyBody='json';n.parameters.jsonBody='={{ JSON.stringify($json) }}';}
const input=child.nodes.find(n=>n.type==='n8n-nodes-base.executeWorkflowTrigger');const prior=child.connections[input.name];child.connections[input.name]={main:[[{node:'Inject Test Boundary',type:'main',index:0}]]};child.connections['Inject Test Boundary']=prior;child.nodes.push({id:'inject-boundary',name:'Inject Test Boundary',type:'n8n-nodes-base.code',typeVersion:2,position:[0,-250],parameters:{mode:'runOnceForAllItems',jsCode:"const c=$input.first().json;if(c.author.name.endsWith('childerror'))throw new Error('SYNTHETIC_CHILD_ERROR');if(c.author.name.endsWith('childempty'))return [];return $input.all();"}});
fs.writeFileSync(path.join(out,'child.json'),JSON.stringify(child,null,2));
for(const [scenario,modes] of Object.entries({mixed:['normal','unverifiable','classfail','empty','synthesisfail','childerror','childempty','after'],stop:['normal','blocked','unscheduled']})){
 const parent=read('parent'),config=JSON.parse(parent.nodes.find(n=>n.name==='Run Config1'||n.name==='Run Config').parameters.jsonOutput);config.limits.retry_wait_ms=1000;
 const dataset={run_id:'synthetic',pages:config.page_urls.map(page_url=>({page_url,fetch_status:'success',discovered_count:0,parsed_count:0,invalid_count:0,complete:true,issues:[]})),input_complete:true,quotes:[],author_inputs:modes.map(mode=>{const url='https://quotes.toscrape.com/author/Fixture-'+mode+'/';return {run_id:'synthetic',author:{author_id:url,bio_url:url,name:'Fixture '+mode,quote_ids:[]},limits:config.limits,identity_quotes:[]};})};
 const seen=new Set();function visit(k){if(seen.has(k))return;seen.add(k);for(const es of parent.connections[k]?.main||[])for(const e of es)visit(e.node);}visit('Prepare Batch');parent.nodes=parent.nodes.filter(n=>seen.has(n.name));parent.connections=Object.fromEntries(Object.entries(parent.connections).filter(([k])=>seen.has(k)));
 parent.nodes.unshift({id:'local-start',name:'Start Local Test',type:'n8n-nodes-base.manualTrigger',typeVersion:1,position:[-600,0],parameters:{}},{id:'local-fixture',name:'Synthetic Dataset',type:'n8n-nodes-base.code',typeVersion:2,position:[-300,0],parameters:{mode:'runOnceForAllItems',jsCode:'return [{json:'+JSON.stringify(dataset)+'}];'}});
 parent.connections['Start Local Test']={main:[[{node:'Synthetic Dataset',type:'main',index:0}]]};parent.connections['Synthetic Dataset']={main:[[{node:'Prepare Batch',type:'main',index:0}]]};
 const call=parent.nodes.find(n=>n.name==='Call Live Author');call.parameters.workflowId={__rl:true,value:child.id,mode:'id'};parent.id='localMock'+scenario;parent.name='LOCAL MOCK - '+scenario;parent.settings={...parent.settings,saveDataSuccessExecution:'all',saveDataErrorExecution:'all'};
 if(parent.nodes.some(n=>n.type==='n8n-nodes-base.httpRequest'))throw new Error('Unexpected live parent request');
 fs.writeFileSync(path.join(out,scenario+'.json'),JSON.stringify(parent,null,2));
}
console.log('Generated localhost-only mixed and stop tests.');


const full=read('parent');full.id='localMockintake';full.name='LOCAL MOCK - Full Intake';full.nodes.find(n=>n.name==='Call Live Author').parameters.workflowId={__rl:true,value:child.id,mode:'id'};
for(const n of full.nodes)if(n.type==='n8n-nodes-base.httpRequest'){const index=n.name==='Fetch Page 1'?0:1;n.parameters.authentication='none';delete n.parameters.genericAuthType;delete n.parameters.bodyParameters;n.parameters.url='http://127.0.0.1:5689/mock';n.parameters.specifyBody='json';n.parameters.jsonBody=JSON.stringify({author:{name:'Fixture intake'},req:{kind:'browserless',label:'intake',attempt:1,body:{url:index===0?'https://quotes.toscrape.com/':'https://quotes.toscrape.com/page/2/'}}});}
fs.writeFileSync(path.join(out,'intake.json'),JSON.stringify(full,null,2));
