const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
function execution(name){const raw=fs.readFileSync(path.join('artifacts',name+'-execution.log'),'utf8');const start=raw.search(/^\{/m);assert(start>=0,'Missing execution JSON');const x=JSON.parse(raw.slice(start));assert.equal(x.status,'success');assert(!x.data.resultData.error);return x;}
function batch(x){const r=x.data.resultData.runData;return (r['Finalize Batch']||r['Finalize Stopped Batch'])[0].data.main[0][0].json;}
function verify(){const refill=execution('refill'),rb=batch(refill);assert.equal(rb.summary.completed_count,1);assert.equal(rb.dossiers[0].research.status,'success');assert.equal(rb.dossiers[0].research.data.qualified_source_count,2);assert.equal(rb.dossiers[0].research.issues.filter(i=>i.code==='SOURCE_ACCESS_DENIED').length,2);const mixed=execution('mixed'),stop=execution('stop'),intake=execution('intake');const m=batch(mixed),s=batch(stop),f=batch(intake);assert.deepEqual([m.summary.completed_count,m.summary.degraded_count,m.summary.failed_count],[3,2,3]);assert.equal(m.dossiers.length,8);assert.equal(new Set(m.dossiers.map(d=>d.author.author_id)).size,8);
 const by=Object.fromEntries(m.dossiers.map(d=>[d.author.name.split(' ').at(-1),d]));assert.equal(by.after.outcome,'completed');assert.equal(by.unverifiable.research.skip_reason,'category_unverifiable');assert.equal(by.classfail.research.skip_reason,'classification_failed');assert.equal(by.classfail.bio.status,'success');assert.equal(by.empty.synthesis.data,null);assert.equal(by.synthesisfail.bio.data.facts.length,1);assert.equal(by.synthesisfail.research.data.facts.length,2);assert(by.childerror.limitations.includes('CHILD_EXECUTION_FAILED'));assert(by.childempty.limitations.includes('CHILD_EMPTY_RESULT'));
 assert.equal(s.summary.stop_reason,'SHARED_AUTH_DENIED');assert.equal(s.dossiers.length,3);assert.equal(stop.data.resultData.runData['Call Live Author'].length,2);assert.equal(s.dossiers[2].bio.skip_reason,'global_service_blocked');
 assert.equal(f.summary.quote_count,4);assert.equal(f.summary.author_count,3);assert(f.summary.input_complete);assert.equal(f.summary.completed_count,3);assert.equal(f.dossiers.find(d=>d.author.name==='Fixture normal').author.quote_ids.length,2);
 const file=fs.existsSync('artifacts/mixed-stop-calls.jsonl')?'artifacts/mixed-stop-calls.jsonl':'artifacts/mock-calls.jsonl';const calls=fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);
 assert.equal(calls.filter(c=>c.author==='Fixture refill'&&c.step==='research_page').length,4);assert.equal(calls.filter(c=>c.author==='Fixture refill'&&c.step==='search_2').length,1);
 for(const mode of ['unverifiable','classfail']){const rows=calls.filter(c=>c.author==='Fixture '+mode);assert(rows.some(c=>c.step==='bio'));assert(!rows.some(c=>/^(search|research)/.test(c.step)));}assert(!calls.some(c=>c.author==='Fixture unscheduled'));assert(!calls.some(c=>c.author==='Fixture empty'&&c.step==='synthesis'));
 const report={engine:'n8n 2.38.7',scope:'Real local n8n engine, HTTP and HTML nodes; external providers replaced with localhost synthetic responses. No real-model semantic validation.',passed:true,scenarios:{refill:{attemptedPages:4,blockedPages:2,qualifiedSources:2,status:'success',historicalIssuesRetained:true},mixed:{authors:8,completed:3,degraded:2,failed:3},sharedStop:{authors:3,scheduled:2,blocked:1},fullIntake:{pages:2,quotes:4,authors:3,completed:3}},durationsMs:Object.fromEntries(Object.entries({mixed,stop,intake}).map(([k,x])=>[k,Date.parse(x.stoppedAt)-Date.parse(x.startedAt)]))};fs.writeFileSync('artifacts/n8n-test-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));return report;}
if(require.main===module)verify();module.exports=verify;
